name: Update AWS Lambda Layer

on:
  push:
    branches:
      - master

jobs:
  update-aws-lambda-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install zip
      run: sudo apt-get install zip

    - name: Create zip package
      run: |
        mkdir -p python/lib/python3.12/site-packages
        cp html_builder/* python/lib/python3.12/site-packages/
        zip -r HTML_Builder_Layer.zip python

    - name: Publish new HTML_Builder_Layer
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
      run: |
        LAYER_VERSION=$(aws lambda publish-layer-version \
          --layer-name HTML_Builder_Layer \
          --zip-file fileb://HTML_Builder_Layer.zip \
          --query Version \
          --output text)
        echo "LAYER_VERSION=${LAYER_VERSION}" >> $GITHUB_ENV

    - name: Delete previous layer version
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
      run: |
        PREVIOUS_LAYER_VERSIONS=$(aws lambda list-layer-versions \
          --layer-name HTML_Builder_Layer \
          --query 'LayerVersions[?Version<`'$LAYER_VERSION'`].Version' \
          --output text)
        for version in $PREVIOUS_LAYER_VERSIONS; do
          aws lambda delete-layer-version --layer-name HTML_Builder_Layer --version-number $version
        done

    - name: Update Lambda to use latest HTML_Builder_Layer
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        LAYER_VERSION: ${{ env.LAYER_VERSION }}
      run: |
        aws lambda update-function-configuration \
          --function-name D2R_Traderie_HTML \
          --layers arn:aws:lambda:$AWS_REGION:$AWS_ACCOUNT_ID:layer:HTML_Builder_Layer:$LAYER_VERSION

  run-aws-lambda:
    runs-on: ubuntu-latest
    needs: update-aws-lambda-layer

    steps:
    - name: Run Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
      run: |
        aws lambda invoke \
          --function-name D2R_Traderie_HTML \
          --payload '{}' response.json
        
        if [ "$(cat response.json)" != "null" ]; then
          echo "Lambda invocation failed with response: $(cat response.json)"
          exit 1  # Exit with an error code
        fi
